// <auto-generated />
using System;
using DonationAPP.Infraestrutura.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DonationAPP.Infraestrutura.SQLite.Migrations
{
    [DbContext(typeof(DbContexto))]
    [Migration("20241115223329_CriacaoSchemaInicial")]
    partial class CriacaoSchemaInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("DonationAPP.Dominio.Modelos.Doacoes.Doacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstituicaoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("DATA");

                    b.Property<Guid>("TipoDoacaoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("TIPODOACAOID");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DOACAO", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
